downloading torch==1.12.1 instead of 1.13.1 resolves issue with force_cuda_install
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory